### ISSUE TITLE
how to use react.js???????

### ISSUE THREAD

**Issue by 1140571314** [qlik-demo-team/qdt-components#1]
how to use qlik sense in react.js???????how to use qlik sense in react.js???????how to use qlik sense in react.jss???????

**Comment by 1140571314** [comment]
how to use react.js???????how to use react.js???????how to use react.js???????how to use react.js???????

**Comment by yianni-ververis** [comment]
Hello,

Use the React Template
https://github.com/qlik-demo-team/qdt-react-template

and here is a demo with the code
https://webapps.qlik.com/qdt-components/react/index.html
