### ISSUE TITLE
Is there a “noInteraction” option? 

### ISSUE THREAD

**Issue by JMC40** [qlik-demo-team/qdt-components#109]
Hello, 

Would it be possible to add a “noInteraction” property for objects? 
We're using qdt components in our mashup code, and use the “noSelections: true” prop. 
We're looking for a way to avoid a chart to display the info when you hover over (meaning we want to see for example the bubbles in a distrib.plot, but prevent users to get any further info about them, as we want to keep them anonymous).  

Thanks a lot, 

Julia Moreno

**Comment by yianni-ververis** [comment]
There is

Just add in your config
```
const viz2 = {
      type: 'QdtViz',
      props: {
        type: 'barchart', 
        id: 'a5e0f12c-38f5-4da9-8f3f-0e4566b28398', 
        height: '300px',      
       noSelections: true,
      },
    };
```

https://github.com/qlik-demo-team/qdt-components/blob/master/src/components/QdtViz.jsx#L13
