### ISSUE TITLE
QdtTable: qMatrix shows only 1000 values

### ISSUE THREAD

**Issue by roysahil** [qlik-demo-team/qdt-components#115]
Using the qdt-components, I have created a grid in my React project. The issue is that source data has more then 25000 rows but my application is rendering only 1000 rows. Probably due to the hypercube limitation. But is there a way to increase its limit? Let me know what changes I should make to get all the rows in my table.

**Comment by roysahil** [comment]
Would appreciate any suggestion or solution for this. This is slowly becoming a show stopper for my project at work. Thanks in advance.

**Comment by yianni-ververis** [comment]
there is not way of changing the limits in the hypercuve results.

What you can do is have a loop to get all data like this

https://community.qlik.com/t5/Qlik-Design-Blog/Getting-all-data-cells-from-app-createCube/bc-p/1470928#M4912

**Comment by yianni-ververis** [comment]
I have added 'getDataInterval' that gets all data based on the given seconds for looping, in QdtMapBox

https://github.com/qlik-demo-team/qdt-components/blob/master/docs/components/QdtMapBox.md

let me know where do you need it

**Comment by roysahil** [comment]
> I have added 'getDataInterval' that gets all data based on the given seconds for looping, in QdtMapBox
> 
> https://github.com/qlik-demo-team/qdt-components/blob/master/docs/components/QdtMapBox.md
> 
> let me know where do you need it

Thank you for responding. This looks promising. Can this be done for QdtTable component please?

**Comment by fkabinoff** [comment]
It's bad for performance and user experience to render so many things rows of a table in the dom at one time. QdtTable includes pagination for this reason.
