### ISSUE TITLE
Facing issues while implementing SSO with Qlik Sense 

### ISSUE THREAD

**Issue by Sumitbaudh** [qlik-demo-team/qdt-components#120]
I want to implement Single-Sign-On(SSO) in Qlik Sense using Qlik Ticket Authentication method.
Where I can append the ticket generated by Qlik server in qdt-components config

**Comment by arunachalamrosslyn** [comment]
Hi, Could you please let me know if you can found a solution for this. If so could you please let me know

**Comment by yianni-ververis** [comment]
You can combine sessions by passing in the config useUniqueSessionID.

https://github.com/qlik-demo-team/qdt-components/blob/master/src/QdtComponents.jsx#L35
