### ISSUE TITLE
Bookmarks 

### ISSUE THREAD

**Issue by VaMusaka** [qlik-demo-team/qdt-components#140]
Is there a way of applying bookmarks and getting bookmarks with qdt components ?

**Comment by VaMusaka** [comment]
Thank you @sezersaruhan 
 I got it to work just using the AppPromise on the basic bookmark api on [Bookmark API](https://help.qlik.com/en-US/sense-developer/September2019/Subsystems/APIs/Content/Sense_ClientAPIs/CapabilityAPIs/qlik-bookmark-interface.htm) and here is my react script  

`componentDidMount() {
		this.qdtComponent = new QdtComponents(this.props.options.config, this.props.options.connections);
		this.getBookmarkList(this.qdtComponent);
	}

	getBookmarkList(qdtComponent) {
		qdtComponent.qAppPromise
		.then(item => item.getList("BookmarkList"))
		.then(item => this.setState({qBookmarkList: item.layout.qBookmarkList.qItems}))
		.catch(err => console.log(err));
	}

	deleteBookmark(qdtComponent, id) {
		qdtComponent.qAppPromise
		.then(item => {item.bookmark.remove(id)})
		.then(() => {
			this.getBookmarkList(qdtComponent)
		}).catch((err) => {console.log(err)});
	}

	applyBookmark(qdtComponent, id) {
		qdtComponent.qAppPromise
		.then(item => item.bookmark.apply(id))
		.catch(err => console.log(err));
	}

	createBookmark(e, qdtComponent){
		e.preventDefault();
		const {title, description} = this.state;
		qdtComponent.qAppPromise
		.then(item => item.bookmark.create(title, description))
		.then(() => {
				this.setState({title: '', description: ''});
				this.getBookmarkList(qdtComponent);
			}
		)
		.catch(err => console.log(err));
	}
`

**Comment by agerner** [comment]
Is there any example for this functionality in Vue?

**Comment by nidhi8953** [comment]
> **Here is example services that i create from bookmarks** **// this going to return all bookmarks that you have in your Qvf** getBookmarks() { return QdtComponent.qdtComponent.qAppPromise .then(item => item.getList("BookmarkList")) .then(item => item.layout.qBookmarkList.qItems) .catch(err => console.log(err)); } **// Pass your bookmark id in function and going to apply** applyBookmark(id) { return QdtComponent.qdtComponent.qDocPromise .then(item => item.applyBookmark(id)) .then(() => { QdtComponent.qdtComponent.qDocPromise.then(item => item.doSave()); }) .catch(err => console.log(err)); } // pass your id and its going to remove your bookmark removeBookmark(id) { return QdtComponent.qdtComponent.qDocPromise .then(item => item.destroyBookmark(id)) .then(() => { QdtComponent.qdtComponent.qDocPromise.then(item => item.doSave()); }) .catch(err => console.log(err)); }

kindly help me with the qdtcompont version number compatible with this code

**Comment by nidhi8953** [comment]
> **Here is example services that i create from bookmarks** **// this going to return all bookmarks that you have in your Qvf** getBookmarks() { return QdtComponent.qdtComponent.qAppPromise .then(item => item.getList("BookmarkList")) .then(item => item.layout.qBookmarkList.qItems) .catch(err => console.log(err)); } **// Pass your bookmark id in function and going to apply** applyBookmark(id) { return QdtComponent.qdtComponent.qDocPromise .then(item => item.applyBookmark(id)) .then(() => { QdtComponent.qdtComponent.qDocPromise.then(item => item.doSave()); }) .catch(err => console.log(err)); } // pass your id and its going to remove your bookmark removeBookmark(id) { return QdtComponent.qdtComponent.qDocPromise .then(item => item.destroyBookmark(id)) .then(() => { QdtComponent.qdtComponent.qDocPromise.then(item => item.doSave()); }) .catch(err => console.log(err)); }
Not able to pass title , in BookMark createBookMarkAPI
Kindly help thanks
