### ISSUE TITLE
Add the standard Sense Selection Bar as a component 

### ISSUE THREAD

**Issue by ChristofSchwarz** [qlik-demo-team/qdt-components#17]
Although I like the "light-weight" QdtSelectionToolbar in many mashups, I miss the standard selection bar for some more advanced users. it has like "prev" "next" "clear all", "lock field", "reverse selection", "search" which I tend to use a lot ... Would be great to have this Standard selection bar also as a QDT

**Comment by yianni-ververis** [comment]
Hello Christof,

I've just added it
https://webapps.qlik.com/qdt-components/react/index.html#/current-selections
