### ISSUE TITLE
Incorrect Selection on - Point Distribution made with Picasso in Demo

### ISSUE THREAD

**Issue by alangrn** [qlik-demo-team/qdt-components#176]
The years are incorrect when making a selection on the Point Distribution made with Picasso demo. 2014 does not select anything and sometime when you click on a 2016 item it filters for year 2014.

**Comment by yianni-ververis** [comment]
Looking...

**Comment by yianni-ververis** [comment]
Fixed in 2.2.13

https://qdt-apps.qlik.com/qdt-components/react/#/picasso-point-distribution.

Thank you

**Comment by alangrn** [comment]
Thank you. Works perfectly now.
