### ISSUE TITLE
NotFound Error Message

### ISSUE THREAD

**Issue by lukearran** [qlik-demo-team/qdt-components#178]
We're attempting to embed Climber's Finance Report using qdt-components, however we're getting a "NotFound" error message, as displayed below.

![Capture](https://user-images.githubusercontent.com/997453/70610699-eae77500-1bfb-11ea-86de-a3914a9d9d79.PNG)

We're setting the below options onto the component, as per below.

```
{
                  type: 'QdtViz',
                  props: {
                    type: 'cl-finance-report', 
                    id: '818ab8a4-b3fc-4f87-b328-22c746163ab0', 
                    height: '400px',      
                    exportData: false,
                    exportImg: false,
                    exportImgOptions: { width: 600, height: 400, format: 'JPG' },
                    exportPdf: false,
                    exportPdfOptions: { documentSize: { width: 300, height: 150 } },
                  }
}
```
Does the QDT component support embedding third-party visualizations? Or is it just Qlik objects which it supports?

Kindest Regards

Luke

**Comment by yianni-ververis** [comment]
Yes of course.

What are the error messages from the console, if you have any or the frames in Network tab

**Comment by lukearran** [comment]
Okay, thanks for your response. 

We're getting a few server error messages at the moment. I've included the log below. But we're getting these error messages on any page, not necessary with the above component.

[localhost-1576164388496.log](https://github.com/qlik-demo-team/qdt-components/files/3956475/localhost-1576164388496.log)

**Comment by yianni-ververis** [comment]
I see a lot of auth issues. nothing related extension or qdt-components. 

qlik.wrenkitchens.com/api/v1/csrf-token:1 Failed to load resource: the server responded with a status of 404 (Not Found)
p-and-l:1 Access to XMLHttpRequest at 'https://qlik.wrenkitchens.com/api/v1/csrf-token' from origin 'http://localhost:4200' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.

qlik.wrenkitchens.com/internal_windows_authentication/?targetId=b5b09e94-71ec-4877-b99a-1652459bfc5e:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)

**Comment by lukearran** [comment]
Thanks for your response,

After further investigation, the error appears to be isolated to my environment, and the CORS issue is due to our dev server is hosted outside of the Qlik Server.

Kindest Regards

Luke
