### ISSUE TITLE
Data not updated correctly after selections

### ISSUE THREAD

**Issue by martow** [qlik-demo-team/qdt-components#180]
**Issue:**
The data in is not correctly updated after making selections with multiple instances of components on the same page. 

**Components**
Issue occurs in following components
- QdtKpi
- QdtPicasso
 <br>

**Steps to reproduce**
- Create two QdtKpi objects on a single page. 
- Add a selection box
- Filter the data with a selection box. 

See also the Qdt-components demo page: 
https://qdt-apps.qlik.com/qdt-components/react/#/kpi

**Comment by yianni-ververis** [comment]
Fixed on 2.2.14.

https://qdt-apps.qlik.com/qdt-components/react/#/kpi

thank you
