### ISSUE TITLE
Filtering in QdtFilter

### ISSUE THREAD

**Issue by martow** [qlik-demo-team/qdt-components#195]
**Issue:**
Search and filter functionality in QdtFilter-component does not work properly. Only one character (last typed one) is used in the result. And the search bar does not display any text. 

See also the Qdt-components demo page:
https://qdt-apps.qlik.com/qdt-components/react/#/filters

**Comment by yianni-ververis** [comment]
Fixed at 2.3.4

https://qdt-apps.qlik.com/qdt-components/react/#/filters

Thank you
Yianni
