### ISSUE TITLE
Qdt-Component Dynamic height for objects ?

### ISSUE THREAD

**Issue by ozgulgozacanlar** [qlik-demo-team/qdt-components#200]
I want to give the objects a constantly changing Height.But Angular 6  only once renders inside the qdt-component.ts
Ex: 
this . qdtComponent . render ( this . Component ,  this . props ,  this . elementRef . nativeElement ); 

Is there any way to redraw the same object when the height changes ?

**Comment by fkabinoff** [comment]
the simplest way is to just call window.resize(). both QdtPicasso and QdtViz will resize on a window resize.
