### ISSUE TITLE
Two instances of qdtComponent connecting to two different apps

### ISSUE THREAD

**Issue by MF0414** [qlik-demo-team/qdt-components#22]
In a react application is the use of qdt-components restricted to a single qlik sense application?

I created two separate instances of qdtComponent that each have a different appId associated with it. When the app Id's are different only one of the components will render correctly and the other returns "Object not found".

When the app ids are the same they both work. And both configs have been verified to work independently.

**Comment by fkabinoff** [comment]
Good question. Its designed to work with more than 1 application, with each instance of the QdtComponents class being able to have its own config. But I honestly havent tested it much. Will have to check it out and get back to you when i have a chance.

**Comment by jonvitale** [comment]
@fkabinoff  Any updates on this. I want to make sure I can connect to multiple apps before I dive in, else I'm going to need to back out and do it the standard AngularJS way (boo).

**Comment by yianni-ververis** [comment]
Are you trying to have 2 different object from 2 different apps on the same page? This will not work.

**Comment by jonvitale** [comment]
@yianni-ververis In theory that may have been something I wanted to do, but not necessarily. I think the basic use case would be to have have (2+) separate templates that each pull from a different Qlik App. Are there any examples of this with qdt-components?

**Comment by yianni-ververis** [comment]
Working on it

**Comment by fkabinoff** [comment]
It should just work? I haven't tested it, but each instance of
qdt-components creates its own connections. So you should just be able to
have to different configs and do something like var qdtComponents1 = new
QdtComponents(config), and var qdtComponents2 = new QdtComponents(config2),
something like that.

**Comment by yianni-ververis** [comment]
In theory it should be fine but I get Angular errors

**Comment by jonvitale** [comment]
breaking errors?

**Comment by yianni-ververis** [comment]
Yes. Requirejs is trying to bootstrap angular twice

**Comment by jonvitale** [comment]
Excellent, I look forward to trying it out!
