### ISSUE TITLE
Types and src not present in 2.5.5 node modules installation

### ISSUE THREAD

**Issue by Zokor** [qlik-demo-team/qdt-components#222]
Hi guys,

Thanks for your hard work on this library.

I use this with Angular, and the types and src were very handy for me to navigate through the API you guys developed. Can you start submitting it again?

Can't recall the version that stripped it out, but i'm using 2.5.5 and it doesn't exist in there.

Thank you

**Comment by yianni-ververis** [comment]
Can you try 3.0?

Here are some examples

https://observablehq.com/collection/@yianni-ververis/qdt-components
