### ISSUE TITLE
How to handle header based authentication with proxy in angular application

### ISSUE THREAD

**Issue by sshelake25** [qlik-demo-team/qdt-components#228]
Does qdt-components support angular@9 version .
How to handle authentication and load table data.

Does anyone did authentication with qlik sense with header/JWT/SAML

**Comment by yianni-ververis** [comment]
Qdt-components does not handle auth. Instead, we use a server that authenticates and passes the jwt token for verification.

https://github.com/qlik-demo-team/qdt-components/blob/master/src/qdtEnigma.js#L57

**Comment by yianni-ververis** [comment]
Yes on the Angular. here is with Angular 10

https://github.com/qlik-demo-team/qdt-angular-template
