### ISSUE TITLE
suppress null/zero values?

### ISSUE THREAD

**Issue by jonvitale** [qlik-demo-team/qdt-components#231]
Hello, for QdtPicasso is there a way to do one or both of the following, like we can in a standard Qlik Sense chart:
1. Turn off "Include null values" for a dimension?
2. Turn off "Include zero values" (including nulls) for a measure?

**Comment by yianni-ververis** [comment]
Try 2.0 an pass it in the hyperCube like 

https://observablehq.com/@yianni-ververis/qdt-components-horizontal-barchart?collection=@yianni-ververis/qdt-components
