### ISSUE TITLE
Error while embedding objects with Create-React-App

### ISSUE THREAD

**Issue by thomaspessato** [qlik-demo-team/qdt-components#235]
I'm trying to use the component as it is demonstrated in the examples. Configured for Qlik Sense Desktop.

I did

```npm install --save qdt-components```

Component:
```javascript

import React from 'react';
import PropTypes from 'prop-types';
import QdtComponents from 'qdt-components';

const options = {
  config: {
    host: "localhost",
    secure: false,
    port: 4848,
    prefix: "",
    appId: "Consumer Sales.qvf"
  },
  connections: { 
    vizApi: true, 
    engineApi: false
  }
}

const qdtComponents = new QdtComponents(options.config, options.connections);

export default class QdtComponent extends React.Component {
  static propTypes = {
    type: PropTypes.string.isRequired,
    props: PropTypes.object.isRequired,
  }
  componentDidMount() {
    const { type, props } = this.props;
    qdtComponents.render(type, props, this.node);
  }

  componentWillUnmount() {
    QdtComponents.unmountQdtComponent(this.node)
  }

  render() {
    return (
      <div ref={(node) => { this.node = node; }} />
    );
  }
}
```

Using the component: 
```javascript
<QdtComponent type={'QdtViz'} props={{ type: 'QdtTable', id: 'ufWRp', height: '300px' }} />
```

Result:
![image](https://user-images.githubusercontent.com/9112010/94690275-49eeb580-0306-11eb-9933-a9c1ca17f741.png)

If I use a barchart, it can filter values, but cannot export data. I'm not sure if I need to import something else (?)

**Comment by thomaspessato** [comment]
I'm using requirejs to load qlik's module and use data. Maybe an angularjs conflict?

**Comment by yianni-ververis** [comment]
This is require.js and angular errors. Qdt-components does not have draggable

**Comment by thomaspessato** [comment]
Yep... but this happens when I use Qdt components and requirejs... I'm using capability APIs and trying to use QdtComponents for regular app.visualization.get() and create(). I'm wondering if I can use both on the same web app or should I just choose one (qdt or requirejs)

**Comment by yianni-ververis** [comment]
qdt-components has no issues with require.js

In React
https://qdt-apps.qlik.com/qdt-components/react/#/embed-object-multi-app

In simple html
https://observablehq.com/@yianni-ververis/qdt-components-embed-objects-from-2-different-apps?collection=@yianni-ververis/qdt-components

**Comment by thomaspessato** [comment]
alright. i'm going to close this issue and do some more testing. if the problem still happens and I discover something, I'll reopen it :) thanks @yianni-ververis
