### ISSUE TITLE
Version 3.0 Release question

### ISSUE THREAD

**Issue by alfredobarroso** [qlik-demo-team/qdt-components#236]
Is there any timeline for the version 3.0 release? Is the code from branch 3.0 stable/usable?

Thanks.

**Comment by ashishpadman** [comment]
I'm also waiting for branch 3.0 to be merged to master branch. The automated procurement tool for the enterprise npm registry in my company only picks up from master branch releases

**Comment by yianni-ververis** [comment]
It is stable and usable, I have multiple examples. As far as moving to master it will happen soon!

**Comment by yianni-ververis** [comment]
Finally Done!!!

I am sorry for the long wait
