### ISSUE TITLE
Re-use enigma instance?

### ISSUE THREAD

**Issue by countnazgul** [qlik-demo-team/qdt-components#24]
I have implementation that is already using `enigma`  to communicate with the Engine. And was thinking if its possible to use Qdt for some visualizations. 

Is it possible to pass the `global` that i have from `enigma` to Qdt or I need to have separate session for Qdt?

**Comment by yianni-ververis** [comment]
Qdt-omponents has already made a connection via the Engine API. You can use the qDoc like

const qdtComponents = new QdtComponents(options.config, options.connections);
      const qDoc = await qdtComponents.qDocPromise;
      const qObject = await qDoc.createSessionObject(qProp);

**Comment by countnazgul** [comment]
Thanks
