### ISSUE TITLE
Custom Error Messages in 3.0

### ISSUE THREAD

**Issue by DrRocket** [qlik-demo-team/qdt-components#241]
I've read in a couple of different places that starting with version 3.0, we'd be able to override Qlik's error message behavior and create our own.  Currently you can get stuck in a loop if there is an issue with the Qlik server where the error keeps popping up as a modal dialog and makes using the rest of the application impossible.

Is there an example anywhere on how to override this behavior in 3.0?

**Comment by yianni-ververis** [comment]
Just pass in the config a timeoutMessage

https://github.com/qlik-demo-team/qdt-components/blob/master/src/qdtEnigma.js#L71
