### ISSUE TITLE
Sample of Stacked Pivot table

### ISSUE THREAD

**Issue by letehaha** [qlik-demo-team/qdt-components#244]
Hey guys, could you please create an example of building a stacked pivot table? I have a custom implementation of the table on my project (because there are a lot of additional business requirements), and I looked a bit at your implementation while developing. But now I need to build a stacked pivot table and I have a few troubles with it. The main one is sorting. In case we need to change the sort order on the default table, we just need to change `qInterColumnSortOrder` (and patch `qSortCriterias` of the dimension to change ASC/DESC). But stacked pivot table not only sorting data by ASC/DESC, but also changing dimension position in the data schema.

For example, there are 3 dimensions in such order: `[Investment, Industry, Region]`. They all have `sortCriteria => qSortByAscii => DESC`. After changing `qInterColumnSortOrder` to `[1, 0, 2]` on the default table, dimension `Industry` will be sorted by DESC, but dimensions will still be displayed as `[Investment, Industry, Region]`. But the stacked pivot table will change dimension order to `[Industry, Investment, Region]`. This behavior isn't documented (or I cannot find it), so I don't know how to fix that. I saw that stacked pivot table using `qEffectiveInterColumnSortOrder` inside its inner structure, but not `qInterColumnSortOrder`. But playing with `qEffectiveInterColumnSortOrder` didn't help me.

It would be nice to have an example of a stacked pivot table, or at least get help with my case :)

**Comment by yianni-ververis** [comment]
https://community.qlik.com/t5/Qlik-Design-Blog/Creating-a-Pivot-Table-with-the-new-GetHyperCubeTreeData-method/ba-p/1631606

**Comment by letehaha** [comment]
Cool!
Just couldn't find this example either on the [website](https://qdt-apps.qlik.com/qdt-components/react/#/) or in the [sources](https://github.com/qlik-demo-team/qdt-components/tree/master/src/components) 🤔 Perhaps the example was forgotten to add, or I just look at the wrong place. Anyway, I hope this example will resolve my problem, so thank you!
