### ISSUE TITLE
QDTSelections shows hidden fields

### ISSUE THREAD

**Issue by frankpacker** [qlik-demo-team/qdt-components#246]
Implementing QdtSelections in Angular 10 with the latest methodology configured as per below:

  selections = {
    component: QdtSelections,
    properties: {
      qSelectionObjectDef: {},
    },
    connection: 2,
    style: {
      width: "100%",
      paddingTop: "0px",
    },
  };

Issue is that hidden fields for Qlik are rendered. Would expect that they would be excluded as per the ordinary selections bar in Qlik.
Is there a configuration option available to add to the above, or can this be updated?

**Comment by tonikautto** [comment]
@yianni-ververis do you have any insights on if this can be configured in the current version of components? Thanks

**Comment by yianni-ververis** [comment]
You can add a custom css class like

```
.MuiMenuItem-root.excluded {
  display: none;
}
```

**Comment by frankpacker** [comment]
The above solution will not solve this issue.
The selections bar component itself displays Qlik fields that have been tagged as hidden. I'm not referring values that have been excluded by selections, which will be hidden by the above class.

The issue here is that if a whole field has been tagged as hidden in the Qlik load script, it is still displayed by the QdtSelections component and there is no class applied to the button rendered that can allow it to be hidden with a method similar to the above.

**Comment by yianni-ververis** [comment]
Can you share an example? I need to debug

**Comment by frankpacker** [comment]
Hi Yianni,

 

Sure, annotated screenshots to follow:

 

 

In the Qlik script, fields are tagged as hidden as follows:



 

 

Ordinarily, these fields will not show at all in the standard selections toolbar:



 

 

 

The issue is that these hidden fields so show in the in the QDT components  (v3) toolbar.

To replicate the issue, tag some fields in a qlik app as hidden then make selections in those fields to observe the QDT componets toolbar.

 

 

 

Regards,

 

Frank Packer

Consultant and UI/UX Designer

Ph: 0457 592 047

**Comment by frankpacker** [comment]
> Can you share an example? I need to debug

Hi Yianni,
Is there any update on this issue?

Cheers!
