### ISSUE TITLE
Need to append vp prefix to fetch require.js and qlik-styles.css 

### ISSUE THREAD

**Issue by miranda-elliott** [qlik-demo-team/qdt-components#35]
I'm trying to use qdt-components in vue. I configured it as follows, per the [vue template](https://github.com/qlik-demo-team/qdt-vue-template) you all have published: 

```
const options = {
  config: {
    host: '<host>',
    secure: true,
    port: 443,
    prefix: '<prefix>',
    appId: '<app-id>',
  },
  connections: {
    vizApi: true,
    engineApi: true,
  },
};

const qdtComponents = new QdtComponents(options.config, options.connections);
```

In simple tutorials for getting started with mashups, I learned to import require.js and qlik-styles.css into the HTML with an URL that includes the prefix of the virtual proxy. For example:

`<script src="https://<host>/<prefix>/resources/assets/external/requirejs/require.js"></script>`

If I understand this library correctly, you define the app configuration and it handles the rest. However, I can see that it's trying to fetch require.js and qlik-styles.css from the host without the prefix, so the request is returning a 301 and showing the following error in Firefox:

`require.js:1
SyntaxError: expected expression, got '<'`

Is this a known bug? How can I resolve this?

**Comment by yianni-ververis** [comment]
You do not need to load require.js in this one. It is something with the config. What is your prefix and your anon virtual proxy?

**Comment by miranda-elliott** [comment]
My prefix is "/test/". In the QMC, the virtual proxy has the prefix "test". Why do you think it's trying to fetch those files without the prefix?

**Comment by yianni-ververis** [comment]
No you still need the prefix but without slashes

Sent from my iPhone
________________________________

**Comment by miranda-elliott** [comment]
It's now fetching from the virtual proxy when I don't use slashes. Thank you!
