### ISSUE TITLE
Windows authentication prompt shown when Ticket authentication is in place for a virtual proxy

### ISSUE THREAD

**Issue by praveena-m** [qlik-demo-team/qdt-components#37]
I have followed the guide for using qdtcomponent for React mashup app, for some reason, I keep getting windows authentication prompt. I have a ticket generated using the API. I have successfully authenticated to Qlik server by requesting image and received qlik session cookie. I even tried passing ticket to connections.useUniqueSessionID with no luck.

Any help on this issue would be greatly appreciated!

![network](https://user-images.githubusercontent.com/1097942/44683359-ff99fc80-a9fa-11e8-9229-7742a1650876.png)

**Comment by miranda-elliott** [comment]
I'm having the same issue. Have you made any progress on resolving this?

**Comment by yianni-ververis** [comment]
In order to do ticketing, we need to modify headers which cannot be done via a browser, only with server side scripting.

**Comment by miranda-elliott** [comment]
@yianni-ververis If this is the case, is it possible to use qdt-components to load objects from a Qlik Sense app that requires authentication? Don't all of Qlik's methods of authentication require headers?

**Comment by fkabinoff** [comment]
That's really odd though. If you have a valid cookie, it should not prompt for authentication...hmm...any more info on this? Was this ever resolved?

**Comment by dreadeyedave** [comment]
I am getting the same issue. I am authenticating via a jwt reverse proxy, however it looks like the request is being made to 
https://example.com/internal_windows_authentication/?targetId=dbc83516-efa7-48ae-91ca-91146d55eefc

and pushing a username password alert

whereas i would expect it to be 
https://example.com/jwt/?targetId=dbc83516-efa7-48ae-91ca-91146d55eefc

And i know i have a valid cookie as I am using to get to the hub/qmc.

**Comment by fkabinoff** [comment]
im closing this. theres nothing in any of these comments that suggests this is a problem with qdt-components. when i look at the first image i can see that when the require.js file is requested its returning a 302 which is what it does when a user doesn't have a valid session cookie for that virtual proxy, and this has nothing to do with qdt-components itself. find me on qlik branch slack if you're having general authentication troubles with qlik and mashups, will try to help there.
