### ISSUE TITLE
Getting error while using this component.

### ISSUE THREAD

**Issue by sbhagana** [qlik-demo-team/qdt-components#38]
Hi, 
While using this component on my application I am getting this error on following line.

componentDidMount() {
    const { type, props } = this.props;
    **qdtComponents.render(type, props, this.node);**
  }
Could you please help me in this. thanks
![image](https://user-images.githubusercontent.com/22980448/44731933-ecbe1f80-ab01-11e8-80b7-b9e43466f724.png)

**Comment by yianni-ververis** [comment]
What are you trying to render? show me the code.

You have to have something like
https://webapps.qlik.com/qdt-components/react/index.html#/picasso-horizontal-barchart

that is calling the render method

**Comment by sbhagana** [comment]
That was some other issue, now it's working fine , thanks
