### ISSUE TITLE
Header authentication

### ISSUE THREAD

**Issue by miranda-elliott** [qlik-demo-team/qdt-components#39]
I want to use header authentication with qdt-components. I have the virtual proxy prefix in the config, but how do I pass the user header and xrf-key header and URL parameter with each call (like in [this example](https://help.qlik.com/en-US/sense-developer/June2018/Subsystems/Platform/Content/Examples/config-header-authentication.htm))? I don't see any documentation around this. Thank you.

**Comment by fkabinoff** [comment]
You don't pass the user header and xrf-key with websocket requests from the browser. What you have to do instead is make a request to a REST endpoint (I use 'qps/user') and pass the user header with that before qdt-components creates any websocket connections. That REST endpoint request will return a set-cookie header and set a cookie that will be passed with every websocket request.

**Comment by ollystephens1** [comment]
I am also trying to authenticate following the instructions [here](https://help.qlik.com/en-US/sense-developer/June2018/Subsystems/Platform/Content/Examples/config-header-authentication.htm), which when run with Postman returns a `Set-Cookie` with my custom proxy etc.

I am running this request on startup in my Angular app, but I am getting a number of different errors:

`Cannot read property 'config' of undefined`

`'Please specify a qConfig global variable' error`

Could anyone please provide some instructions as to how to actually authenticate through Angular?
