### ISSUE TITLE
Can we run react component with react-native?

### ISSUE THREAD

**Issue by MotovilovSA** [qlik-demo-team/qdt-components#4]
Trying to run react component with react native framework, but ran into error: "can't find variable document qdt-components.js:27:384242"

**Comment by fkabinoff** [comment]
qdt-components uses ReactDom.render method, which will not work with React Native. Also, all components are built with html. You may be able to fork and use something like https://github.com/archriss/react-native-render-html and build your own render function, but haven't tried it myself.
