### ISSUE TITLE
Can't create react vizualization component with pre-selected fields filter

### ISSUE THREAD

**Issue by gchehab** [qlik-demo-team/qdt-components#40]
I am using qdt-components react on my applications and wanted to create visualizations with pre-selected filters. I have seen an plain .js implementation that used something like:

app = qlik.openApp('12334ac4-61e0-4476-b227-1540f2004022', config);
    // Object Filter
    app.field('ORG_SUPER_PADR_ID').selectMatch('2607', true);
    app.getObject('obj-name', '1ab7f73e-48c7-4688-9e6d-d8027c9b4f42', { noSelections : true, noIteraction : false});

What would be the react api equivalent of the app.field call, and how is it used?

**Comment by yianni-ververis** [comment]
Most of our examples are in React.
https://webapps.qlik.com/qdt-components/react/index.html

Regarding the app.field, in he QdtComponents class do,

const qDoc = await qdtComponents.qDocPromise;
const qField = await qDoc.getField('ORG_SUPER_PADR_ID');
qField.selectMatch('2607', true);
OR 
qField.selectValues([{ qText: 'Heating Temp' }], true, true); 
OR
qField.select([1,5], true, true);

**Comment by gchehab** [comment]
It did the trick, thanks a lot!
