### ISSUE TITLE
Custom error handling on react API

### ISSUE THREAD

**Issue by gchehab** [qlik-demo-team/qdt-components#41]
Our application should embed visualizations from QlikSense.  Any issue with the QAP server triggers a Modal that only allowed to reload the entire application -- if the error persisted the same error is shown over and over again rendering the application unusable.

What is the best way to override, inhibit or create a call back instead of the default error treatment ?  I would like to, in case of errors, present a simple message to the user that would not lock the entire application.

**Comment by fkabinoff** [comment]
We'll take a look at that

**Comment by fkabinoff** [comment]
we don't have a way to hook into either the capability api qlik interface or enigma session interface, in which this is somewhat configurable. that is not going to change for 2.x or below. this will change for 3.0 and above.
