### ISSUE TITLE
Third Party Libraries and qdt-components 

### ISSUE THREAD

**Issue by alangrn** [qlik-demo-team/qdt-components#43]
Has anyone tried to use third party libraries with qdt-components in React?

I have tried 2 differently libraries and have create my own qdt-chart.

I can get it them to render but the selections both return an enigma error. I have used the same code in the Qlik-react-start applications and they work fine so trying to figure out what needs to change.

**Comment by fkabinoff** [comment]
I'm not sure how you're doing it, or what you're seeing. Need more info.

**Comment by alangrn** [comment]
Thanks Francis. I realised that I was missing a parameter in the select function. I can now get this rmplementation to work with third party chartiing libraries. Great work guys.
