### ISSUE TITLE
Qdt-Current Selections not picking up selections

### ISSUE THREAD

**Issue by Pelumis** [qlik-demo-team/qdt-components#45]
i am currently building a mashup using Qdt-components and React, which has been going really well, but i have noticed that the current selections is not actually working properly , it seem that it only takes in selections on the page  it lands on after a page refresh but when navigating to other pages  and making selections the current selection bar is not being update with those selections. 

Does anyone have any ideas how to fix this? 
Thanks

**Comment by Pelumis** [comment]
hi
your example does show selections  when navigating to the other page , i am wondering if that is the same implantation as https://webapps.qlik.com/qdt-components/react/index.html#/current-selections which is the one i am currently trying to use.

The version i am using  of Qdt is v1.3.11

![image](https://user-images.githubusercontent.com/34349620/47083626-1a257080-d209-11e8-9cbf-939184fe95f5.png)

**Comment by fkabinoff** [comment]
I'm wondering if you are creating new instances on page change...check your network tab for websockets see what you got going on

**Comment by yianni-ververis** [comment]
check 1.3.22

**Comment by yianni-ververis** [comment]
All selection issues are resolved in the latest release, please update.

Closing the issue. Please reopen if you see it again. 

Thank you
