### ISSUE TITLE
Node.js - React - Authentication to Server

### ISSUE THREAD

**Issue by robcastle** [qlik-demo-team/qdt-components#49]
Do you have an example of how to authenticate to a Qlik server? My app connects fine to your demo server but I can't get it to work against my server that requires authentication

**Comment by fkabinoff** [comment]
there's really no one flow. what kind of authentication are you using on your qlik sense virtual proxy and are you using the vizApi in qdt-components?

**Comment by robcastle** [comment]
I am using visApi in qdt-components.

One of our other apps uses certificates to connect to the Qlik server. I was trying to make that work but the docs that I was following didn't seem to work. I am using node.js with react and qdt-components with react template to place visualizations in my app. 

For user authentication to the qlik server we are using windows authentication. But I'm fine with using certificates if I can get information on how to make it work with qdt-components on react.

**Comment by robcastle** [comment]
Maybe I'm missing something. I can pass certificates  if I'm making the API calls myself (without react). But if I'm using the react components, I don't know where the entry point is for the request to add the certificate. Do I need to modify the qdt-components source code? or is there a way to pass the react component options for the certificates?

**Comment by fkabinoff** [comment]
you would never want to pass certificates on the front-end. the front-end is trustless. qdt-components is a front-end library. it doesnt handle this itself.
