### ISSUE TITLE
Please do not minify the dist code

### ISSUE THREAD

**Issue by dennisat** [qlik-demo-team/qdt-components#52]
We cannot debug it
![image](https://user-images.githubusercontent.com/26453466/49819536-019f8580-fd76-11e8-8687-5e9687f9eea2.png)

**Comment by dennisat** [comment]
The final app will minify the code, not the module itself.
It doesn't offer anything.

**Comment by yianni-ververis** [comment]
Done

Min and not min in dist folder

https://github.com/qlik-demo-team/qdt-components/pull/83

https://github.com/qlik-demo-team/qdt-components/tree/master/dist
