### ISSUE TITLE
Clicking directly into a filter from a dropdown doesn't save selections

### ISSUE THREAD

**Issue by sunpar** [qlik-demo-team/qdt-components#53]
Reproduce:

- Make two filters with this example def:

{
    type: 'QdtFilter',
    props: {
      cols: ['Region'],
      placeholder: 'Region',
      expanded: false,
      autoSortByState: 0,
      showStateInDropdown: true
    }

{
    type: 'QdtFilter',
    props: {
      cols: ['Brand'],
      placeholder: 'Brand',
      expanded: false,
      autoSortByState: 0,
      showStateInDropdown: true
    }

Select a value in one drop down, then click directly on the other filter to open the other drop down -- WHILE the first drop down is still open.

**Comment by yianni-ververis** [comment]
All selection issues are resolved in the latest release, please update.

Closing the issue. Please reopen if you see it again.

Thank you
