### ISSUE TITLE
User interaction doesn't work, internal Qlik error

### ISSUE THREAD

**Issue by eazybit** [qlik-demo-team/qdt-components#55]
Hi,

We are using Qdt components inside our Angular 6 project. 
Here is the package dependencies:
"@angular/animations": "~6.0.0",
    "@angular/common": "~6.0.0",
    "@angular/compiler": "~6.0.0",
    "@angular/core": "~6.0.0",
    "@angular/forms": "~6.0.0",
    "@angular/http": "~6.0.0",
    "@angular/platform-browser": "~6.0.0",
    "@angular/platform-browser-dynamic": "~6.0.0",
    "@angular/router": "~6.0.0",
    "core-js": "^2.5.4",
    "jquery": "^3.3.1",
    "qdt-components": "^1.3.13",
    "rxjs": "~6.3.3",
    "zone.js": "~0.8.26"

Here is the configuration object:
config: {
        "host": "<our server address>",
        "secure": true,
        "port": 443,
        "prefix": "",
        "appId": "<our app ID>"
    },
    connections: {
        "vizApi": true,
        "engineApi": true
    }

Here is the 'QdtViz' configuration
        type: 'QdtViz',
        props: {
            id: '<our object ID>',
            height: '300px'
        }

The Angular UI successfully launch the Qdt component, but it has a lot of console errors which pointing our AngularJS code on the server. The user interaction is not working. When I click the filter panel, no dropdown is shown. When I click the grid header, it's not doing sorting.
If I directly open the Qlik app through URL, everything works just fine.

Here is the screenshot of the console error:
<img width="639" alt="screen shot 2018-12-21 at 2 59 10 pm" src="https://user-images.githubusercontent.com/4863743/50366851-1081f700-0531-11e9-8439-584a9881bca2.png">

**Comment by fkabinoff** [comment]
have no idea. sorry just getting around to this. hopefully resolved by now. if not open a new issue. closing due to age.
