### ISSUE TITLE
error in withSelectionObject component

### ISSUE THREAD

**Issue by stefanhofmann2** [qlik-demo-team/qdt-components#56]

**Comment by stefanhofmann2** [comment]
in the componentWillMount part, after createSessionObject
   ...
      const qObject = await qDoc.createSessionObject(qProp);
the call to
      qDoc.on('changed', () => { this.update(); });
should be changed by 
     qObject.on('changed', () => { this.update(); });
to get changes on session object

**Comment by stefanhofmann2** [comment]
Should the name of the component not be better withSelectionObject instead of withListObject?

**Comment by yianni-ververis** [comment]
Here is working fine

https://webapps.qlik.com/qdt-components/react/index.html#/current-selections

**Comment by yianni-ververis** [comment]
fixed in 1.3.22

Thnx
