### ISSUE TITLE
Current Selections not working in Sense November 2018

### ISSUE THREAD

**Issue by alangrn** [qlik-demo-team/qdt-components#57]
If I use Sense September 2017 the current Selections show when I make a selection. On Sense Nov 2018 Patch 2 the selections are applied but the current selection component does not rerender. When I change routes the component renders correctly. What do I need to change?

**Comment by yianni-ververis** [comment]
please update to the latest version. All issues on selections and multiple objects should be resolved.

Closing the issue. Please reopen if the problem persists.
