### ISSUE TITLE
Applying Theme

### ISSUE THREAD

**Issue by VaMusaka** [qlik-demo-team/qdt-components#58]
Currently, l have not seen any documentation relating to how to apply a theme to an app or objects when using QDT-Components. Although a theme is applied to a published app when pulling objects with QDT-Components the objects in the mashup are using the default qlik sense theme. Is there a way of specifying which theme l would like to be used in the mashup? if not are there any plans of adding this into QDT-Components?

**Comment by nlaffey** [comment]
This is also an issue for me. I'd expect objects rendered via qdt-components to inject the css file of the theme which is assigned on the project but this doesn't appear to be the case, only the `/resources/autogenerated/qlik-styles.css` is applied.

**Comment by frank-packer** [comment]
Would like to see this added as well. It'd be great if qdt-components applied any theme that's assigned to the app.

**Comment by fkabinoff** [comment]
got you
