### ISSUE TITLE
Sheet Object Not Found

### ISSUE THREAD

**Issue by VaMusaka** [qlik-demo-team/qdt-components#59]
I have been trying to bring a complete Qlik Sense Sheet in the mashup using QDT-Components in React js but get an error "**The Visualisation was not found on the server. This extension is not available :  {0}(sheet)**". 

![image](https://user-images.githubusercontent.com/6652780/52711310-68653900-2f89-11e9-8787-982526b464e6.png)

**Comment by nlaffey** [comment]
I'm also interested in some direction on how to go about rendering sheets. I'm getting a similar error: 
![image](https://user-images.githubusercontent.com/2968323/53188819-20bb5e80-35d4-11e9-8248-29ce69b2486a.png)

**Comment by Garethp** [comment]
@yianni-ververis Are sheets just not supported?

**Comment by yianni-ververis** [comment]
No. The Viz API is only for objects

https://help.qlik.com/en-US/sense-developer/June2019/Subsystems/APIs/Content/Sense_ClientAPIs/CapabilityAPIs/VisualizationAPI/get-method.htm

**Comment by fkabinoff** [comment]
don't render sheets. bad practice. just iframe if you really want to use them. but sheets lose all responsiveness when iframed. i usually suggest against embedding sheets at all except in very certain cases. but in any case, qdt-components will not be handling that.
