### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by MF0414** [qlik-demo-team/qdt-components#6]
We are authenticating to our Qlik Sense Server with JWT, how can I incorporate authentication with this library?

**Comment by MF0414** [comment]
We incorporated jwt authentication by sending the token in the header, the authentication api does not work well with this approach.

**Comment by vsalesa** [comment]
How do managed to include jwt token in the  component request?

**Comment by yianni-ververis** [comment]
Soon

**Comment by DrRocket** [comment]
Is there any update on this?  I would like to use JWT auth with qdt-components in my angular app but can't get it to work.
