### ISSUE TITLE
Extending qdt-components

### ISSUE THREAD

**Issue by robcastle** [qlik-demo-team/qdt-components#60]
I'm looking for design advice related to extending qdt-components. I want to use the same pattern that qdt-components uses to get data for QdtPicasso (i.e. withHyperCube class), but I want to substitute my own charting library instead of picassso. My question is what is the best way to achieve my objective. Should I inherit from QdtPicasso or should I copy the QdtPicasso code into my project without inheriting or should I make a copy of qdt-components and put my extension code in there.

Or is there too much picasso specific code in withHyperCube to accomplish this without rewriting withHyperCube significantly

**Comment by alangrn** [comment]
I have used the above implementation and use fusionCharts as my charting library so it will work with a third party library.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
