### ISSUE TITLE
Qdt-Current Selections not working if multiple components on the page

### ISSUE THREAD

**Issue by robcastle** [qlik-demo-team/qdt-components#61]
I'm using the qdt-components on Qlik Sense Feb2019 in a react app. I have placed a QdtPicasso chart and several KPIs (QdtViz) on a page with the QdtCurrentSelections component.

When I have the KPIs (QdtViz) on the page, the QdtPicasso chart does not pick up selections made from QdtCurrentSelections. But if I comment out the KPI components QdtPicasso filters correctly.

Have you seen this issue?

**Comment by yianni-ververis** [comment]
Please check the latest 1.3.20 and let me know

**Comment by yianni-ververis** [comment]
check 1.3.22

**Comment by yianni-ververis** [comment]
All selection issues are resolved in the latest release, please update.

Closing the issue. Please reopen if you see it again.

Thank you
