### ISSUE TITLE
QdtButton: Export Data

### ISSUE THREAD

**Issue by dreadeyedave** [qlik-demo-team/qdt-components#62]
Hi,

I have included an export data button, in a qdt-component, however when it is clicked the link that it is trying to retrieve the data from is via 'internal_windows_authentication'. 

Is this just case with the api, or is there a condition setting where it can go to another reverse proxy?

Thanks David

**Comment by dreadeyedave** [comment]
![image](https://user-images.githubusercontent.com/36961142/56661252-47ac1480-6699-11e9-9978-1b6f3e78e239.png)

**Comment by yianni-ververis** [comment]
We do not have it as a param yet. It takes the url from the config, so if you have already auth, you should not have any issue.
