### ISSUE TITLE
Qdt Search - Safari bug

### ISSUE THREAD

**Issue by JMC40** [qlik-demo-team/qdt-components#63]
Hello, 

We are using a Search/filter template that uses qdt components. It can be found in the demo site: https://webapps.qlik.com/qdt-components/react/index.html#/search. 

We're observing an issue when using our apps with this filter through **Safari**.  The initial load of the app with safari shows that Qlik doesn't update on the screen after making selections. However, after refreshing the page, it does start to work fine and update the Qlik (listbox) components on the screen.  

The search template works fine on Chrome or other explorers, though. 

It seems like safari is doing something strange when connecting for the first time? 
We've been looking at this and the web-socket appears to have different user info coming back. Seems like the selections might be firing on a separate session, while the visualisation renders on a session with no selections. 

Could you please have a look and see if this Safari bug could be fixed? 
Many thanks in advance, we really like this search template and would like to use it in our apps!

**Comment by JMC40** [comment]
Note:  You can reproduce the issue for troubleshooting by using a new private window in Safari each time.

**Comment by yianni-ververis** [comment]
check 1.3.22

**Comment by JMC40** [comment]
Hi! 
@yianni-ververis , how do I check that, please? 

Thank you!

**Comment by yianni-ververis** [comment]
npm install qdt-components@1.3.22 --save

**Comment by yianni-ververis** [comment]
On in the demo
https://qdt-apps.qlik.com/qdt-components/react/#/search

**Comment by JMC40** [comment]
Fantastic. 
Thanks a lot!

**Comment by yianni-ververis** [comment]
I just test with my safari 12.1.1 and I did not see any errors anywhere.

Closing the issue.

**Comment by yianni-ververis** [comment]
it seems that Safari is creating different ws ids for viz and engine api.

Try this in your config

  connections: {
    vizApi: true,
    engineApi: true,
    useUniqueSessionID: Math.random().toString(32).substr(2, 8),
  },

**Comment by JMC40** [comment]
Thanks, Yianni! 
I tried your suggestion and it seems that is working fine! 
GREAT. 

Thank you!
