### ISSUE TITLE
QdtTable renders only 2 colums

### ISSUE THREAD

**Issue by roysahil** [qlik-demo-team/qdt-components#64]
I am using qdtcomponents in one of my React projects at work. Till now most of the components have worked like a charm. However strangely, the QdtTable component is rendering only 2 columns. Have checked the code in QdtTable.jsx but unable to figure out yet. Any help will be appreciated. 
Thanks in advance.

**Comment by yianni-ververis** [comment]
Fixed at 1.3.18

**Comment by roysahil** [comment]
Thanks a lot 😊
