### ISSUE TITLE
Filter Object Props Documentation

### ISSUE THREAD

**Issue by MF0414** [qlik-demo-team/qdt-components#7]
What props does a filter object take?

The examples are great, but there is no api documentation as far as I can see. This repo would benefit greatly from a well defined list of methods and arguments for object properties.

**Comment by fkabinoff** [comment]
Agreed, and it's coming.

**Comment by MF0414** [comment]
Is there anyway you could post which props the filter objects take on this issue? We have all of the Qvis objects working perfectly. We're good on the setup, we just can't tell from the source which props the filter object is expecting.

**Comment by fkabinoff** [comment]
The filter object expects either a 'cols' prop or a 'qListObjectDef' prop. The 'cols' prop works just like the viz api 'cols' prop, and the 'qListObjectDef' is the same as documented in engine api.  The 'cols' prop takes priority, so if you define that, the 'qListObjectDef' prop will be ignored. 

This is the same general pattern for all the custom components, they will all take either 'cols' prop, or a 'qListObjectDef' prop or 'qHyperCubeDef' prop, whichever one is appropriate. Some components take additional props.

Going to be pushing documentation later today.

**Comment by MF0414** [comment]
We really appreciate it! This api is really well done, thanks again.
