### ISSUE TITLE
Latest Build

### ISSUE THREAD

**Issue by dreadeyedave** [qlik-demo-team/qdt-components#8]
Hi,

This all looks great btw, I am running the react template, and have been working with both the npm version and the latest build.

One thing with the latest build version, is I am currently connecting via an anonymous reverse proxy on our qliksense server, and i am being requested authentication via an alert, it provides the data for the graph, but appears that some objects are being forced through windows authentication and failing. And this wasnt happening with the earlier npm version.

Thanks D

**Comment by yianni-ververis** [comment]
How are you setting the proxy? there should not be a slash in the prefix

**Comment by yianni-ververis** [comment]
https://webapps.qlik.com/qdt-components/plain-html/picasso-horizontalbarchart.html
