### ISSUE TITLE
Adding own components

### ISSUE THREAD

**Issue by dreadeyedave** [qlik-demo-team/qdt-components#9]
Hi,

I am trying to add my own components / make amendments to existing ones, e.g. the qdtFilter can only be named 'Dropdown'.

Please can you help/advise me on the best way to do that? Would I need an object wrapper as per the method in the repo [https://github.com/fkabinoff/qlik-react-starter](url)?

Thanks D

**Comment by dreadeyedave** [comment]
and would that be the Qdt-components.jsx in components?

**Comment by yianni-ververis** [comment]
Yes that would be it but we are not sure if renaming the component is the right approach.

You can recompile in your local repo with any naming convention you want. Just type npm start and use the dist folder.

**Comment by dreadeyedave** [comment]
Hi Yianni,

Thanks - I figured out the structure and have a version that is running uncompiled so that I can dev my own components. Have made changes to the Filter so that it now takes a title, happy to contribute, although I am sure you guys could make that change if you wanted it.

Cheers

**Comment by yianni-ververis** [comment]
You can definitely contribute and we encourage that. Please commit and do a pull request.

Just do not change the component name.

**Comment by yianni-ververis** [comment]
And thank you for your contribution
