### ISSUE TITLE
scatterplot colorExpression with newlines causes issues with applyPatches

### ISSUE THREAD

**Issue by dselgo** [qlik-demo-team/qdt-components#90]
This is a pretty specific issue, but it is one that stumped me for a while. I am trying to make a scatterplot that is colored by expression. I create my chart properties and then pass them to QdtComponents via the options prop, and I use setOptions (ApplyPatches) whenever I modify these properties to force a change. It should also be noted that when I create these chart properties I use multi-line strings for my expressions in order to increase readability.

What I have found is that when I have colorExpression on a scatterPlot with newlines in it, the GetLayout response after an ApplyPatches is weird:
![image](https://user-images.githubusercontent.com/23660205/58963081-8b0aa000-877a-11e9-85c2-e09178521aa6.png)

That block of text with newlines is the color expression I am using. It looks like no properties after the color expression are being included, so the chart fails to update.

As a workaround I can just not make my colorExpressions multi-line, even though it does decrease readability. I'm not sure if this is qdt-component specific or a problem with the Visualization API though.

EDIT: I actually found the same behavior with a bar chart as well. So it may not be limited to scatterplots.

**Comment by fkabinoff** [comment]
Wow sorry just getting to this. This is a limitation of the Visualization API. Using template literals should do it. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

**Comment by dselgo** [comment]
No problem, but all of our expression blocks are wrapped in template literals (most of the set analysis values are variables). We may just need to add a set of escaped backticks so that what gets sent is also wrapped in backticks.

Thanks for following up on this 😄

**Comment by fkabinoff** [comment]
Instead of escaping backticks, just use the ${} and put backticks in there.
Should work.
